steps:
  # Install library  
  - id: 'install'
    name: 'python:3.7-slim'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - 'pip install -r requirements.txt pip install -e . '
  # Run static python code check    
  - id: 'python-linter-check'
    name: 'python:3.7-slim'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - 'flake8 --ignore=E501 --exit-zero ml_repo_test/'
    waitFor: 'install'
  # run unit tests for Python functions
  - id: 'python-unit-tests'
    name: 'python:3.7-slim'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - 'python -B -m pytest ml_repo_test/tests'
    waitFor: 'install'