# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/00_core.ipynb (unless otherwise specified).

__all__ = ["add"]

# Cell
import datetime

print(datetime.datetime.now())


def add(a, b):
    return a + b
